### ISSUE TITLE
Better approach to PDF output? probably

### ISSUE THREAD

**Issue by AlexanderSelzer** [VISdiary/diary-lib#5]
This seems like a much better solution.
https://www.npmjs.com/package/html-pdf

I'll try reimplementing this with it, and seing if it works well.

**Comment by AlexanderSelzer** [comment]
do you like it? @zpiman :)

**Comment by zpiman** [comment]
nice

**Comment by AlexanderSelzer** [comment]
@zpiman is it ok to delete the `tolib` branch

**Comment by zpiman** [comment]
hmm what I did in `tolib` is I wrapped the code with an API-type class. However I think it is it is a little overkill so I guess exposing just a `generate` function is much better way to do it. So I guess it is safe to remove. However I will make a local backup on my fork just in case....

**Comment by AlexanderSelzer** [comment]
@zpiman great.

Now that the main library is clean, I'd start with the CLI generator, if you're not already working on it?

The diary-app, will it be web-based (with an API to render the diary), or built with something like node-webkit?

**Comment by zpiman** [comment]
Well I am not working on it right now but I guess next week I might have some time during the school trip. I will see what I can do. If you want you can have a look at my spaghetti code (if it makes any scene to you). Basically now I am working on the calendar. (Make the functions such as adding quotes and deadlines interactive and intuitive)

**Comment by zpiman** [comment]
And I guess we can close this as resolved in ae7f6a0d771fbf55a35f5a and move on to https://github.com/VISdiary/diary-app
